apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e2e-tests-go-tjjqoxnb-workflow-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/e2e-tests-go-tjjqoxnb-workflow